#!/usr/bin/env Rscript

# =============================================================================
# TVP-GVAR INTEREST-RATE CHANNEL DIAGNOSTIC (NO MCMC)
#
# Purpose
# -------
# Test whether the positive medium-horizon equity response to a +GPR shock is
# supported by the endogenous decline in policy/short rates.
#
# This script uses the already-estimated dominant-unit [GPR,VIX] posterior.
# It DOES NOT re-estimate the model.
#
# Scenarios
# ---------
# FULL
#   Original saved model.
#
# RATE_CF1_zero_current_foreign_rate_to_equity
#   Set Lambda0(foreign_r)=0 only in each country equity equation.
#
# RATE_CF2_zero_current_and_lag1_foreign_rate_to_equity
#   Set Lambda0/Lambda1(foreign_r)=0 only in each country equity equation.
#   This measures the direct weakly-exogenous foreign-rate loading into equity.
#
# RATE_CF3_freeze_all_country_rate_path
#   Strong path intervention. For the GPR IRF, every country r response is fixed
#   to exactly zero at every horizon. The country rate equations are replaced by
#   the constraints r_i(h)=0, while all non-rate equations remain active.
#   This removes BOTH domestic and international propagation generated by the
#   endogenous rate response. It is the main test of the hypothesis:
#       GPR -> rates fall -> equities are supported / recover.
#
# Interpretation of RATE_CF3
# --------------------------
# monetary_support = FULL equity response - rate-frozen equity response
#   > 0 : endogenous rate response raises/supports equity relative to no-rate move
#   < 0 : endogenous rate response depresses equity relative to no-rate move
#
# Important caveat
# ----------------
# RATE_CF3 is a post-estimation path intervention / mechanism diagnostic, not a
# newly estimated structural monetary-policy model and not a causal policy rule.
# =============================================================================

options(stringsAsFactors = FALSE)

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
posterior_file <- Sys.getenv(
  "TVPGVAR_POSTERIOR_RDA",
  "prior_artifact/results/predDens_dominant_gpr_vix.rda"
)
irf_file <- Sys.getenv(
  "TVPGVAR_IRF_RDA",
  "prior_artifact/results/irf_dominant_gpr_vix.rda"
)
out_dir <- Sys.getenv(
  "TVPGVAR_RATE_CF_OUT",
  "results/interest_rate_channel_diagnostic"
)
selected_dates <- trimws(strsplit(
  Sys.getenv(
    "TVPGVAR_RATE_CF_DATES",
    "2003Q1,2008Q3,2014Q3,2020Q1,2022Q1,2023Q4"
  ),
  ",",
  fixed = TRUE
)[[1]])
selected_dates <- selected_dates[nzchar(selected_dates)]

shock_pct <- as.numeric(Sys.getenv("TVPGVAR_GPR_SHOCK_PCT", "10"))
horizon_req <- as.integer(Sys.getenv("TVPGVAR_RATE_CF_HORIZON", "12"))
focus_h <- as.integer(trimws(strsplit(
  Sys.getenv("TVPGVAR_RATE_CF_FOCUS_HORIZONS", "0,1,4,8,12"),
  ",",
  fixed = TRUE
)[[1]]))
check_cf_stability <- tolower(
  Sys.getenv("TVPGVAR_RATE_CF_CHECK_STABILITY", "1")
) %in% c("1", "true", "yes", "y")
max_draws_per_date <- as.integer(Sys.getenv("TVPGVAR_RATE_CF_MAX_DRAWS", "0"))

if (!is.finite(shock_pct) || shock_pct <= 0) {
  stop("TVPGVAR_GPR_SHOCK_PCT must be positive.")
}
if (!is.finite(horizon_req) || horizon_req < 0L) {
  stop("TVPGVAR_RATE_CF_HORIZON must be >= 0.")
}
if (is.na(max_draws_per_date) || max_draws_per_date < 0L) {
  stop("TVPGVAR_RATE_CF_MAX_DRAWS must be >= 0.")
}

dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
for (f in c(posterior_file, irf_file)) {
  if (!file.exists(f)) stop("Missing required saved result: ", f)
}

# -----------------------------------------------------------------------------
# Load saved posterior + IRF
# -----------------------------------------------------------------------------
loaded_post <- load(posterior_file)
if (!all(c("predDens", "Data.setup") %in% loaded_post)) {
  stop(
    "Posterior RDA must contain predDens and Data.setup. Found: ",
    paste(loaded_post, collapse = ", ")
  )
}
loaded_irf <- load(irf_file)
if (!all(c("IRF_post", "stable_mask") %in% loaded_irf)) {
  stop(
    "IRF RDA must contain IRF_post and stable_mask. Found: ",
    paste(loaded_irf, collapse = ", ")
  )
}

xglobal <- as.matrix(Data.setup$bigx)
storage.mode(xglobal) <- "double"
units <- as.character(Data.setup$countries)
country_units <- if (!is.null(Data.setup$country_units)) {
  as.character(Data.setup$country_units)
} else {
  setdiff(units, "GL")
}

if (!"GL" %in% units) stop("Dominant unit GL not found.")
var_names <- colnames(xglobal)
if (is.null(var_names)) stop("Data.setup$bigx lacks column names.")
if (!identical(tail(var_names, 2L), c("GL_gpr", "GL_vix"))) {
  stop("Expected final dominant variables GL_gpr, GL_vix.")
}

rate_vars <- paste0(country_units, "_r")
equity_vars <- paste0(country_units, "_deq")
if (!all(rate_vars %in% var_names)) {
  stop("Missing country rate variable(s): ", paste(setdiff(rate_vars, var_names), collapse = ", "))
}
if (!all(equity_vars %in% var_names)) {
  stop("Missing country equity variable(s): ", paste(setdiff(equity_vars, var_names), collapse = ", "))
}

# Exact W matrices from estimation.
globalG <- lapply(predDens, `[[`, "W")
if (any(vapply(globalG, is.null, logical(1)))) {
  if (is.null(Data.setup$gW)) stop("No saved W matrices found.")
  globalG <- Data.setup$gW
}
if (is.null(names(globalG)) || !all(units %in% names(globalG))) names(globalG) <- units
if (length(predDens) != length(units)) stop("predDens/unit count mismatch.")
if (length(globalG) != length(units)) stop("Global W/unit count mismatch.")

irf_dates <- dimnames(IRF_post)[[1]]
irf_vars <- dimnames(IRF_post)[[2]]
irf_h_names <- dimnames(IRF_post)[[3]]
if (is.null(irf_dates) || is.null(irf_vars)) stop("IRF_post lacks dimnames.")
if (!identical(irf_vars, var_names)) {
  stop("Saved IRF variable order differs from Data.setup$bigx.")
}

saved_h <- suppressWarnings(as.integer(irf_h_names))
if (anyNA(saved_h)) saved_h <- seq_len(dim(IRF_post)[3]) - 1L
horizon <- min(horizon_req, max(saved_h))
focus_h <- sort(unique(focus_h[focus_h >= 0L & focus_h <= horizon]))
if (!length(focus_h)) stop("No requested focus horizons are available.")
selected_dates <- intersect(selected_dates, irf_dates)
if (!length(selected_dates)) stop("No requested dates exist in saved IRF.")

n_draws <- dim(IRF_post)[4]
if (!all(dim(stable_mask) == c(length(irf_dates), n_draws))) {
  stop("stable_mask dimensions do not match IRF_post.")
}
if (any(vapply(predDens, function(z) dim(z$ALPHA)[4], integer(1)) != n_draws)) {
  stop("Posterior ALPHA draw count differs across units / from IRF_post.")
}

# -----------------------------------------------------------------------------
# Scenarios
# -----------------------------------------------------------------------------
scenarios <- c(
  "FULL",
  "RATE_CF1_zero_current_foreign_rate_to_equity",
  "RATE_CF2_zero_current_and_lag1_foreign_rate_to_equity",
  "RATE_CF3_freeze_all_country_rate_path"
)

scenario_definitions <- data.frame(
  scenario = scenarios,
  type = c("baseline", "coefficient switch-off", "coefficient switch-off", "path intervention"),
  restriction = c(
    "Original fitted model; no restriction.",
    "Set Lambda0(foreign_r)=0 only in every country equity equation.",
    "Set Lambda0(foreign_r)=0 and Lambda1(foreign_r)=0 only in every country equity equation.",
    "Replace every country rate equation in the IRF propagation by r_i(h)=0 for all horizons; solve remaining non-rate equations exactly."
  ),
  interpretation = c(
    "Baseline.",
    "Tests contemporaneous foreign-rate loading into equity.",
    "Tests direct current+lagged foreign-rate loading into equity.",
    "Main monetary-support test: FULL minus rate-frozen equity response > 0 means the endogenous rate path supports equity."
  ),
  stringsAsFactors = FALSE
)
write.csv(scenario_definitions, file.path(out_dir, "00_scenario_definitions.csv"), row.names = FALSE)

expected_wex <- c(
  "foreign_y", "foreign_dp", "foreign_r", "foreign_de", "foreign_deq",
  "global_gpr", "global_vix"
)

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
split_alpha <- function(A) {
  if (length(dim(A)) != 3L) stop("Single-draw ALPHA must be [time, coefficient, equation].")
  tags <- dimnames(A)[[2]]
  eq <- dimnames(A)[[3]]
  if (is.null(tags) || is.null(eq)) stop("ALPHA lacks coefficient/equation dimnames.")

  block <- function(tag, optional = FALSE) {
    ii <- which(tags == tag)
    if (!length(ii)) {
      if (!optional) stop("Missing coefficient block: ", tag)
      return(array(0, dim = c(dim(A)[1], 0L, dim(A)[3])))
    }
    A[, ii, , drop = FALSE]
  }

  lag_tags <- grep("^Ylag[0-9]+$", unique(tags), value = TRUE)
  if (!length(lag_tags)) stop("No domestic lag blocks in ALPHA.")
  lag_nums <- sort(unique(as.integer(sub("^Ylag", "", lag_tags))))
  if (anyNA(lag_nums) || !identical(lag_nums, seq_len(max(lag_nums)))) {
    stop("Domestic lag labels are not contiguous.")
  }
  p <- max(lag_nums)

  list(
    Lambda0 = block("Wex", optional = TRUE),
    Lambda = lapply(seq_len(p), function(j) block(paste0("Wexlag", j), optional = TRUE)),
    Theta = lapply(seq_len(p), function(j) block(paste0("Ylag", j))),
    p = p,
    eq = eq
  )
}

slice_coef <- function(arr, tt, nrow_out) {
  if (dim(arr)[2] == 0L) return(matrix(0, nrow = nrow_out, ncol = 0L))
  z <- arr[tt, , , drop = FALSE]
  z <- matrix(z, nrow = dim(arr)[2], ncol = nrow_out)
  t(z)
}

get_W <- function(i, cc) {
  if (!is.null(names(globalG)) && cc %in% names(globalG)) return(as.matrix(globalG[[cc]]))
  as.matrix(globalG[[i]])
}

eq_index <- function(eq_names, cc, suffix) {
  out <- match(paste0(cc, "_", suffix), eq_names)
  if (is.na(out)) out <- match(suffix, eq_names)
  out
}

stabilize_cov <- function(S, eps = 1e-10) {
  S <- as.matrix(S)
  S <- (S + t(S)) / 2
  ev <- eigen(S, symmetric = TRUE, only.values = TRUE)$values
  mn <- min(ev)
  if (!is.finite(mn)) stop("Non-finite covariance eigenvalue.")
  if (mn <= eps) S <- S + diag(abs(mn) + eps, nrow(S))
  S
}

spectral_radius <- function(F) {
  if (!length(F)) stop("No transition matrices.")
  K <- nrow(F[[1]])
  p <- length(F)
  if (p == 1L) return(as.numeric(max(Mod(eigen(F[[1]], only.values = TRUE)$values))))
  top <- do.call(cbind, F)
  lower <- cbind(diag(K * (p - 1L)), matrix(0, K * (p - 1L), K))
  companion <- rbind(top, lower)
  as.numeric(max(Mod(eigen(companion, only.values = TRUE)$values)))
}

qsum <- function(x) {
  x <- x[is.finite(x)]
  if (!length(x)) {
    return(c(low90=NA_real_, low68=NA_real_, median=NA_real_, high68=NA_real_, high90=NA_real_, mean=NA_real_, positive_share=NA_real_, negative_share=NA_real_, n=0))
  }
  qq <- quantile(x, c(.05,.16,.50,.84,.95), names = FALSE)
  c(
    low90=qq[1], low68=qq[2], median=qq[3], high68=qq[4], high90=qq[5],
    mean=mean(x), positive_share=mean(x>0), negative_share=mean(x<0), n=length(x)
  )
}

# -----------------------------------------------------------------------------
# Coefficient switch-offs
# -----------------------------------------------------------------------------
mutate_rate_switch <- function(lam0, lam_lags, cc, eq_names, wex_names, scenario) {
  if (scenario == "FULL" || scenario == "RATE_CF3_freeze_all_country_rate_path" || cc == "GL") {
    return(list(lam0=lam0, lam_lags=lam_lags))
  }
  if (!identical(wex_names, expected_wex)) {
    stop("Unexpected Wex order for ", cc, ": ", paste(wex_names, collapse=", "))
  }
  fr_j <- match("foreign_r", wex_names)
  deq_i <- eq_index(eq_names, cc, "deq")
  if (is.na(fr_j) || is.na(deq_i)) stop("Cannot locate foreign_r/equity equation for ", cc)

  if (scenario == "RATE_CF1_zero_current_foreign_rate_to_equity") {
    lam0[deq_i, fr_j] <- 0
  } else if (scenario == "RATE_CF2_zero_current_and_lag1_foreign_rate_to_equity") {
    lam0[deq_i, fr_j] <- 0
    if (!length(lam_lags) || ncol(lam_lags[[1]]) == 0L) stop("Lag-1 Wex block missing for ", cc)
    lam_lags[[1]][deq_i, fr_j] <- 0
  } else {
    stop("Unknown rate scenario: ", scenario)
  }
  list(lam0=lam0, lam_lags=lam_lags)
}

# -----------------------------------------------------------------------------
# Rebuild G/H/F for one posterior draw
# -----------------------------------------------------------------------------
build_state <- function(tt, draw, scenario) {
  locals <- vector("list", length(units))

  for (i in seq_along(units)) {
    cc <- units[[i]]
    A4 <- predDens[[i]]$ALPHA
    A_draw <- A4[, , , draw, drop = FALSE]
    A_draw <- array(A_draw, dim=dim(A4)[1:3], dimnames=dimnames(A4)[1:3])
    V <- split_alpha(A_draw)
    k_i <- length(V$eq)
    Wi <- get_W(i, cc)
    if (nrow(Wi) < k_i) stop("W has fewer rows than own variables for ", cc)

    expected_foreign <- nrow(Wi) - k_i
    if (cc == "GL") {
      if (expected_foreign != 0L) stop("GL should have zero weakly-exogenous rows.")
      wex_names <- character(0)
    } else {
      if (expected_foreign != 7L) stop("Expected 7 Wex rows for ", cc, "; found ", expected_foreign)
      if (is.null(rownames(Wi))) stop("W matrix lacks row names for ", cc)
      wex_names <- rownames(Wi)[(k_i+1L):nrow(Wi)]
      if (!identical(wex_names, expected_wex)) {
        stop("Wex row order mismatch for ", cc, ". Found: ", paste(wex_names, collapse=", "))
      }
    }

    lam0 <- slice_coef(V$Lambda0, tt, k_i)
    lam_lags <- lapply(seq_len(V$p), function(kk) slice_coef(V$Lambda[[kk]], tt, k_i))

    # q=1 in the current dominant-unit architecture. For p=2, Wexlag2 is zero.
    for (kk in seq_len(V$p)) {
      if (ncol(lam_lags[[kk]]) == 0L && expected_foreign > 0L) {
        if (kk <= 1L) stop("Missing Wexlag1 block for ", cc)
        lam_lags[[kk]] <- matrix(0, nrow=k_i, ncol=expected_foreign)
      }
      if (ncol(lam_lags[[kk]]) != expected_foreign) {
        stop("Foreign-lag/W mismatch for ", cc, " lag ", kk)
      }
    }

    sw <- mutate_rate_switch(lam0, lam_lags, cc, V$eq, wex_names, scenario)
    lam0 <- sw$lam0
    lam_lags <- sw$lam_lags

    A0 <- cbind(diag(k_i), -lam0)
    if (ncol(A0) != nrow(Wi)) stop("A0/W mismatch for ", cc, " under ", scenario)

    H_i <- vector("list", V$p)
    for (kk in seq_len(V$p)) {
      theta <- slice_coef(V$Theta[[kk]], tt, k_i)
      B <- cbind(theta, lam_lags[[kk]])
      if (ncol(B) != nrow(Wi)) stop("B/W mismatch for ", cc, " lag ", kk, " under ", scenario)
      H_i[[kk]] <- B %*% Wi
    }

    S4 <- predDens[[i]]$SIGMApost
    S <- S4[tt, , , draw, drop = FALSE]
    S <- matrix(S, nrow=k_i, ncol=k_i)
    locals[[i]] <- list(G=A0 %*% Wi, H=H_i, S=S, k=k_i)
  }

  max_p <- max(vapply(locals, function(z) length(z$H), integer(1)))
  G <- do.call(rbind, lapply(locals, `[[`, "G"))
  H <- lapply(seq_len(max_p), function(kk) {
    do.call(rbind, lapply(locals, function(z) {
      if (kk <= length(z$H)) z$H[[kk]] else matrix(0, nrow=z$k, ncol=ncol(G))
    }))
  })
  F <- lapply(H, function(h) solve(G, h))
  S_post <- lapply(locals, `[[`, "S")
  rho <- if (check_cf_stability) spectral_radius(F) else NA_real_
  list(G=G, H=H, F=F, S=S_post, rho=rho)
}

# Structural innovation in the dominant block: GL_gpr -> GL_vix.
make_structural_innovation <- function(state) {
  gl_i <- match("GL", units)
  S_gl <- stabilize_cov(state$S[[gl_i]])
  if (!all(dim(S_gl) == c(2L,2L))) stop("Dominant covariance must be 2x2.")
  L <- t(chol(S_gl))
  shock_gl <- L[,1]
  u <- unlist(lapply(seq_along(units), function(i) {
    k_i <- nrow(state$S[[i]])
    if (i == gl_i) shock_gl else rep(0, k_i)
  }), use.names=FALSE)
  if (length(u) != ncol(xglobal)) stop("Innovation stack dimension mismatch.")
  u
}

normalize_impact <- function(impact_raw, shock_pct) {
  gpr_j <- match("GL_gpr", var_names)
  if (is.na(gpr_j) || !is.finite(impact_raw[gpr_j]) || abs(impact_raw[gpr_j]) < 1e-12) {
    stop("Cannot normalize GL_gpr impact.")
  }
  target <- log1p(shock_pct/100)
  impact_raw * (target / impact_raw[gpr_j])
}

make_structural_irf <- function(state, horizon, shock_pct) {
  K <- ncol(xglobal)
  u <- make_structural_innovation(state)
  impact <- normalize_impact(as.numeric(solve(state$G, u)), shock_pct)
  out <- matrix(0, nrow=K, ncol=horizon+1L, dimnames=list(var_names, as.character(0:horizon)))
  out[,1L] <- impact
  if (horizon >= 1L) {
    for (h in seq_len(horizon)) {
      for (lag in seq_len(min(length(state$F), h))) {
        out[,h+1L] <- out[,h+1L] + state$F[[lag]] %*% out[,h-lag+1L]
      }
    }
  }
  out
}

# Strong mechanism intervention: set every country rate response to zero at
# every horizon. Replace rate equations by r_i(h)=0 and solve all remaining
# equations. This also removes indirect propagation from the rate path.
make_rate_frozen_irf <- function(state, horizon, shock_pct) {
  K <- ncol(xglobal)
  rate_idx <- match(rate_vars, var_names)
  if (anyNA(rate_idx)) stop("Cannot locate all country rate variables.")
  free_idx <- setdiff(seq_len(K), rate_idx)
  if (!(match("GL_gpr", var_names) %in% free_idx)) stop("GL_gpr unexpectedly constrained.")

  Gff <- state$G[free_idx, free_idx, drop=FALSE]
  if (nrow(Gff) != length(free_idx)) stop("Constrained G dimension mismatch.")

  # Under r=0, only non-rate columns of lag matrices remain relevant.
  Hff <- lapply(state$H, function(hh) hh[free_idx, free_idx, drop=FALSE])
  Fff <- lapply(Hff, function(hh) solve(Gff, hh))
  rho <- if (check_cf_stability) spectral_radius(Fff) else NA_real_

  u <- make_structural_innovation(state)
  impact_free_raw <- as.numeric(solve(Gff, u[free_idx]))
  impact_raw <- rep(0, K)
  impact_raw[free_idx] <- impact_free_raw
  impact <- normalize_impact(impact_raw, shock_pct)
  impact[rate_idx] <- 0

  out <- matrix(0, nrow=K, ncol=horizon+1L, dimnames=list(var_names, as.character(0:horizon)))
  out[,1L] <- impact

  if (horizon >= 1L) {
    for (h in seq_len(horizon)) {
      rhs_free <- rep(0, length(free_idx))
      for (lag in seq_len(min(length(state$H), h))) {
        rhs_free <- rhs_free + Hff[[lag]] %*% out[free_idx, h-lag+1L]
      }
      out[free_idx, h+1L] <- as.numeric(solve(Gff, rhs_free))
      out[rate_idx, h+1L] <- 0
    }
  }

  list(path=out, rho=rho)
}

# -----------------------------------------------------------------------------
# Allocate compact arrays
# -----------------------------------------------------------------------------
nd <- length(selected_dates)
ns <- length(scenarios)
nc <- length(country_units)
nhf <- length(focus_h)

eq_direct <- array(NA_real_, dim=c(nd,ns,nc,nhf,n_draws), dimnames=list(date=selected_dates, scenario=scenarios, country=country_units, horizon=as.character(focus_h), draw=NULL))
eq_cumulative <- eq_direct
rate_direct <- array(NA_real_, dim=c(nd,nc,nhf,n_draws), dimnames=list(date=selected_dates, country=country_units, horizon=as.character(focus_h), draw=NULL))

rho_arr <- array(NA_real_, dim=c(nd,ns,n_draws), dimnames=list(date=selected_dates, scenario=scenarios, draw=NULL))
solve_ok <- array(FALSE, dim=c(nd,ns,n_draws), dimnames=list(date=selected_dates, scenario=scenarios, draw=NULL))
used_draw <- matrix(FALSE, nrow=nd, ncol=n_draws, dimnames=list(selected_dates,NULL))
max_baseline_reproduction_error <- 0

# -----------------------------------------------------------------------------
# Main loop
# -----------------------------------------------------------------------------
cat("\n============================================================\n")
cat(" TVP-GVAR INTEREST-RATE CHANNEL DIAGNOSTIC — NO MCMC\n")
cat(" Posterior: ", posterior_file, "\n", sep="")
cat(" IRF:       ", irf_file, "\n", sep="")
cat(" Dates:     ", paste(selected_dates, collapse=", "), "\n", sep="")
cat(" Horizon:   0-", horizon, "\n", sep="")
cat(" Focus h:   ", paste(focus_h, collapse=", "), "\n", sep="")
cat(" Shock:     +", shock_pct, "% GL_gpr\n", sep="")
cat("============================================================\n\n")

for (d_i in seq_along(selected_dates)) {
  ddate <- selected_dates[[d_i]]
  tt <- match(ddate, irf_dates)
  draws <- which(stable_mask[tt,])
  if (!length(draws)) {
    warning("No original stable draws at ", ddate, "; skipping.")
    next
  }
  if (max_draws_per_date > 0L && length(draws) > max_draws_per_date) draws <- draws[seq_len(max_draws_per_date)]
  used_draw[d_i,draws] <- TRUE
  cat("Date ", ddate, ": using ", length(draws), "/", sum(stable_mask[tt,]), " original stable draws\n", sep="")

  for (jj in seq_along(draws)) {
    draw <- draws[[jj]]
    base_state <- build_state(tt, draw, "FULL")
    base_path <- make_structural_irf(base_state, horizon, shock_pct)

    saved <- IRF_post[tt, , seq_len(horizon+1L), draw, drop=FALSE]
    saved <- matrix(saved, nrow=length(var_names), ncol=horizon+1L, dimnames=list(var_names,as.character(0:horizon)))
    err <- max(abs(base_path-saved), na.rm=TRUE)
    max_baseline_reproduction_error <- max(max_baseline_reproduction_error, err)
    if (!is.finite(err) || err > 1e-7) {
      stop("Baseline reconstruction mismatch at ", ddate, ", draw ", draw, ". max abs error = ", signif(err,8))
    }

    paths <- list(FULL=base_path)
    rhos <- list(FULL=base_state$rho)
    oks <- list(FULL=TRUE)

    # Coefficient switch-offs.
    for (scenario in c("RATE_CF1_zero_current_foreign_rate_to_equity", "RATE_CF2_zero_current_and_lag1_foreign_rate_to_equity")) {
      ans <- tryCatch({
        st <- build_state(tt, draw, scenario)
        pa <- make_structural_irf(st, horizon, shock_pct)
        list(ok=TRUE, path=pa, rho=st$rho)
      }, error=function(e) {
        warning("Counterfactual failed: date=", ddate, ", draw=", draw, ", scenario=", scenario, " | ", conditionMessage(e))
        list(ok=FALSE, path=NULL, rho=NA_real_)
      })
      if (ans$ok) paths[[scenario]] <- ans$path
      rhos[[scenario]] <- ans$rho
      oks[[scenario]] <- ans$ok
    }

    # Strong path intervention.
    scenario <- "RATE_CF3_freeze_all_country_rate_path"
    ans <- tryCatch({
      z <- make_rate_frozen_irf(base_state, horizon, shock_pct)
      list(ok=TRUE, path=z$path, rho=z$rho)
    }, error=function(e) {
      warning("Rate-path intervention failed: date=", ddate, ", draw=", draw, " | ", conditionMessage(e))
      list(ok=FALSE, path=NULL, rho=NA_real_)
    })
    if (ans$ok) paths[[scenario]] <- ans$path
    rhos[[scenario]] <- ans$rho
    oks[[scenario]] <- ans$ok

    # Diagnostics per scenario.
    for (scenario in scenarios) {
      s_i <- match(scenario, scenarios)
      solve_ok[d_i,s_i,draw] <- isTRUE(oks[[scenario]])
      rho_arr[d_i,s_i,draw] <- rhos[[scenario]]
    }

    # Baseline rate response: rates are level variables, so DO NOT cumulate.
    for (c_i in seq_along(country_units)) {
      vv <- paste0(country_units[[c_i]], "_r")
      v_i <- match(vv, var_names)
      z <- as.numeric(base_path[v_i,])
      for (h_i in seq_along(focus_h)) {
        h <- focus_h[[h_i]]
        rate_direct[d_i,c_i,h_i,draw] <- z[h+1L]
      }
    }

    # Equity direct and cumulative responses.
    for (scenario in scenarios) {
      if (is.null(paths[[scenario]])) next
      s_i <- match(scenario, scenarios)
      path <- paths[[scenario]]
      for (c_i in seq_along(country_units)) {
        vv <- paste0(country_units[[c_i]], "_deq")
        v_i <- match(vv, var_names)
        z <- as.numeric(path[v_i,])
        cz <- cumsum(z)
        for (h_i in seq_along(focus_h)) {
          h <- focus_h[[h_i]]
          eq_direct[d_i,s_i,c_i,h_i,draw] <- z[h+1L]
          eq_cumulative[d_i,s_i,c_i,h_i,draw] <- cz[h+1L]
        }
      }
    }

    if (jj %% 25L == 0L || jj == length(draws)) {
      cat("  ", ddate, ": draw ", jj, "/", length(draws), " complete\n", sep="")
    }
  }
}

# -----------------------------------------------------------------------------
# Summaries
# -----------------------------------------------------------------------------
summarise_equity <- function(arr, representation) {
  rows <- list(); rr <- 0L
  for (d_i in seq_len(nd)) for (s_i in seq_len(ns)) for (c_i in seq_len(nc)) for (h_i in seq_len(nhf)) {
    qs <- qsum(arr[d_i,s_i,c_i,h_i,])
    rr <- rr + 1L
    rows[[rr]] <- data.frame(
      date=selected_dates[d_i], scenario=scenarios[s_i], country=country_units[c_i],
      variable=paste0(country_units[c_i],"_deq"), representation=representation,
      horizon=focus_h[h_i], median=qs[["median"]], mean=qs[["mean"]],
      low68=qs[["low68"]], high68=qs[["high68"]], low90=qs[["low90"]], high90=qs[["high90"]],
      positive_share=qs[["positive_share"]], negative_share=qs[["negative_share"]], draws=as.integer(qs[["n"]]),
      stringsAsFactors=FALSE
    )
  }
  do.call(rbind,rows)
}

summarise_rates <- function(arr) {
  rows <- list(); rr <- 0L
  for (d_i in seq_len(nd)) for (c_i in seq_len(nc)) for (h_i in seq_len(nhf)) {
    qs <- qsum(arr[d_i,c_i,h_i,])
    rr <- rr + 1L
    rows[[rr]] <- data.frame(
      date=selected_dates[d_i], country=country_units[c_i], variable=paste0(country_units[c_i],"_r"),
      representation="direct_rate_IRF", horizon=focus_h[h_i], median=qs[["median"]], mean=qs[["mean"]],
      low68=qs[["low68"]], high68=qs[["high68"]], low90=qs[["low90"]], high90=qs[["high90"]],
      positive_share=qs[["positive_share"]], negative_share=qs[["negative_share"]], draws=as.integer(qs[["n"]]),
      stringsAsFactors=FALSE
    )
  }
  do.call(rbind,rows)
}

equity_summary <- rbind(
  summarise_equity(eq_direct,"direct_change_IRF"),
  summarise_equity(eq_cumulative,"cumulative_level_effect")
)
rate_summary <- summarise_rates(rate_direct)

write.csv(equity_summary, file.path(out_dir,"01_equity_rate_channel_posterior_summary.csv"), row.names=FALSE)
write.csv(rate_summary, file.path(out_dir,"02_baseline_rate_IRF_posterior_summary.csv"), row.names=FALSE)

# Baseline rate sign counts.
rate_sign_rows <- list(); rr <- 0L
for (idx in split(seq_len(nrow(rate_summary)), interaction(rate_summary$date,rate_summary$horizon,drop=TRUE,lex.order=TRUE))) {
  d <- rate_summary[idx,,drop=FALSE]
  rr <- rr + 1L
  rate_sign_rows[[rr]] <- data.frame(
    date=d$date[1], horizon=d$horizon[1], countries=nrow(d),
    negative_rate_median_countries=sum(d$median<0,na.rm=TRUE),
    positive_rate_median_countries=sum(d$median>0,na.rm=TRUE),
    significantly_negative_68=sum(d$high68<0,na.rm=TRUE),
    significantly_positive_68=sum(d$low68>0,na.rm=TRUE),
    median_cross_country_rate_response=median(d$median,na.rm=TRUE),
    stringsAsFactors=FALSE
  )
}
rate_sign_counts <- do.call(rbind,rate_sign_rows)
rate_sign_counts <- rate_sign_counts[order(match(rate_sign_counts$date,selected_dates),rate_sign_counts$horizon),,drop=FALSE]
write.csv(rate_sign_counts, file.path(out_dir,"03_baseline_rate_response_sign_counts.csv"), row.names=FALSE)

# Equity baseline comparisons.
eq_cum <- subset(equity_summary, representation=="cumulative_level_effect")
base <- eq_cum[eq_cum$scenario=="FULL",c("date","country","horizon","median","low68","high68")]
names(base)[4:6] <- c("baseline_median","baseline_low68","baseline_high68")
comp <- merge(eq_cum,base,by=c("date","country","horizon"),all.x=TRUE,sort=FALSE)
comp$delta_median_vs_full <- comp$median-comp$baseline_median
comp$ratio_to_full <- ifelse(abs(comp$baseline_median)>1e-12,comp$median/comp$baseline_median,NA_real_)
comp$baseline_positive <- comp$baseline_median>0
comp$counterfactual_positive <- comp$median>0
comp$positive_to_nonpositive_flip <- comp$baseline_positive & !comp$counterfactual_positive
comp$sign_changed_vs_full <- sign(comp$median)!=sign(comp$baseline_median)
# Positive monetary_support means the endogenous rate response SUPPORTS equity.
comp$monetary_support_median <- ifelse(
  comp$scenario=="RATE_CF3_freeze_all_country_rate_path",
  comp$baseline_median-comp$median,
  NA_real_
)
comp <- comp[order(match(comp$date,selected_dates),match(comp$scenario,scenarios),match(comp$country,country_units),comp$horizon),,drop=FALSE]
write.csv(comp,file.path(out_dir,"04_equity_rate_scenario_vs_FULL.csv"),row.names=FALSE)

# Compact decision table.
decision_rows <- list(); rr <- 0L
for (idx in split(seq_len(nrow(comp)),interaction(comp$date,comp$scenario,comp$horizon,drop=TRUE,lex.order=TRUE))) {
  d <- comp[idx,,drop=FALSE]
  nzb <- is.finite(d$baseline_median)&abs(d$baseline_median)>1e-12
  rr <- rr + 1L
  decision_rows[[rr]] <- data.frame(
    date=d$date[1], scenario=d$scenario[1], horizon=d$horizon[1], countries=nrow(d),
    baseline_positive_countries=sum(d$baseline_median>0,na.rm=TRUE),
    counterfactual_positive_countries=sum(d$median>0,na.rm=TRUE),
    positive_to_nonpositive_flips=sum(d$positive_to_nonpositive_flip,na.rm=TRUE),
    any_sign_flips=sum(d$sign_changed_vs_full,na.rm=TRUE),
    median_abs_full=median(abs(d$baseline_median),na.rm=TRUE),
    median_abs_counterfactual=median(abs(d$median),na.rm=TRUE),
    median_ratio_to_full=if(any(nzb)) median(d$ratio_to_full[nzb],na.rm=TRUE) else NA_real_,
    countries_with_positive_monetary_support=if(d$scenario[1]=="RATE_CF3_freeze_all_country_rate_path") sum(d$monetary_support_median>0,na.rm=TRUE) else NA_integer_,
    countries_with_negative_monetary_support=if(d$scenario[1]=="RATE_CF3_freeze_all_country_rate_path") sum(d$monetary_support_median<0,na.rm=TRUE) else NA_integer_,
    median_monetary_support=if(d$scenario[1]=="RATE_CF3_freeze_all_country_rate_path") median(d$monetary_support_median,na.rm=TRUE) else NA_real_,
    stringsAsFactors=FALSE
  )
}
decision <- do.call(rbind,decision_rows)
decision <- decision[order(match(decision$date,selected_dates),match(decision$scenario,scenarios),decision$horizon),,drop=FALSE]
write.csv(decision,file.path(out_dir,"05_equity_rate_channel_decision_table.csv"),row.names=FALSE)

# Stability / solve diagnostics.
stab_rows <- list(); rr <- 0L
for (d_i in seq_len(nd)) for (s_i in seq_len(ns)) {
  used <- which(used_draw[d_i,])
  if (!length(used)) next
  ok <- solve_ok[d_i,s_i,used]
  rho <- rho_arr[d_i,s_i,used]
  rho_ok <- rho[ok & is.finite(rho)]
  rr <- rr + 1L
  stab_rows[[rr]] <- data.frame(
    date=selected_dates[d_i], scenario=scenarios[s_i], original_stable_draws_used=length(used),
    solve_success=sum(ok), solve_success_share=mean(ok), stability_checked=check_cf_stability,
    counterfactual_stable_draws=if(check_cf_stability) sum(rho_ok<1) else NA_integer_,
    counterfactual_stable_share_within_success=if(check_cf_stability&&length(rho_ok)) mean(rho_ok<1) else NA_real_,
    median_counterfactual_rho=if(check_cf_stability&&length(rho_ok)) median(rho_ok) else NA_real_,
    p95_counterfactual_rho=if(check_cf_stability&&length(rho_ok)) as.numeric(quantile(rho_ok,.95,names=FALSE)) else NA_real_,
    stringsAsFactors=FALSE
  )
}
stability_summary <- do.call(rbind,stab_rows)
write.csv(stability_summary,file.path(out_dir,"06_rate_channel_stability_summary.csv"),row.names=FALSE)

# Counterfactual-stable matched-draw robustness.
matched_rows <- list(); rr <- 0L
full_s <- match("FULL",scenarios)
for (d_i in seq_len(nd)) {
  used <- which(used_draw[d_i,])
  if (!length(used)) next
  for (s_i in seq_len(ns)) {
    keep <- used[solve_ok[d_i,s_i,used]]
    if (check_cf_stability && length(keep)) {
      rrho <- rho_arr[d_i,s_i,keep]
      keep <- keep[is.finite(rrho)&rrho<1]
    }
    if (!length(keep)) next
    for (c_i in seq_len(nc)) for (h_i in seq_len(nhf)) {
      zf <- eq_cumulative[d_i,full_s,c_i,h_i,keep]
      zc <- eq_cumulative[d_i,s_i,c_i,h_i,keep]
      qb <- qsum(zf); qc <- qsum(zc)
      rr <- rr + 1L
      matched_rows[[rr]] <- data.frame(
        date=selected_dates[d_i],scenario=scenarios[s_i],country=country_units[c_i],horizon=focus_h[h_i],matched_draws=length(keep),
        full_median=qb[["median"]],full_low68=qb[["low68"]],full_high68=qb[["high68"]],
        cf_median=qc[["median"]],cf_low68=qc[["low68"]],cf_high68=qc[["high68"]],
        delta_median_vs_full=qc[["median"]]-qb[["median"]],
        monetary_support_median=if(scenarios[s_i]=="RATE_CF3_freeze_all_country_rate_path") qb[["median"]]-qc[["median"]] else NA_real_,
        ratio_to_full=if(is.finite(qb[["median"]])&&abs(qb[["median"]])>1e-12) qc[["median"]]/qb[["median"]] else NA_real_,
        full_positive=qb[["median"]]>0,cf_positive=qc[["median"]]>0,
        positive_to_nonpositive_flip=qb[["median"]]>0&&qc[["median"]]<=0,
        sign_changed_vs_full=sign(qb[["median"]])!=sign(qc[["median"]]),
        stringsAsFactors=FALSE
      )
    }
  }
}

if (length(matched_rows)) {
  matched <- do.call(rbind,matched_rows)
  matched <- matched[order(match(matched$date,selected_dates),match(matched$scenario,scenarios),match(matched$country,country_units),matched$horizon),,drop=FALSE]
  write.csv(matched,file.path(out_dir,"07_equity_rate_cf_stable_matched_country.csv"),row.names=FALSE)

  rows <- list(); kk <- 0L
  for (idx in split(seq_len(nrow(matched)),interaction(matched$date,matched$scenario,matched$horizon,drop=TRUE,lex.order=TRUE))) {
    d <- matched[idx,,drop=FALSE]
    nzb <- is.finite(d$full_median)&abs(d$full_median)>1e-12
    kk <- kk+1L
    rows[[kk]] <- data.frame(
      date=d$date[1],scenario=d$scenario[1],horizon=d$horizon[1],countries=nrow(d),matched_draws=min(d$matched_draws),
      full_positive_countries=sum(d$full_median>0,na.rm=TRUE),cf_positive_countries=sum(d$cf_median>0,na.rm=TRUE),
      positive_to_nonpositive_flips=sum(d$positive_to_nonpositive_flip,na.rm=TRUE),any_sign_flips=sum(d$sign_changed_vs_full,na.rm=TRUE),
      median_abs_full=median(abs(d$full_median),na.rm=TRUE),median_abs_cf=median(abs(d$cf_median),na.rm=TRUE),
      median_ratio_to_full=if(any(nzb)) median(d$ratio_to_full[nzb],na.rm=TRUE) else NA_real_,
      countries_with_positive_monetary_support=if(d$scenario[1]=="RATE_CF3_freeze_all_country_rate_path") sum(d$monetary_support_median>0,na.rm=TRUE) else NA_integer_,
      median_monetary_support=if(d$scenario[1]=="RATE_CF3_freeze_all_country_rate_path") median(d$monetary_support_median,na.rm=TRUE) else NA_real_,
      stringsAsFactors=FALSE
    )
  }
  matched_decision <- do.call(rbind,rows)
  matched_decision <- matched_decision[order(match(matched_decision$date,selected_dates),match(matched_decision$scenario,scenarios),matched_decision$horizon),,drop=FALSE]
  write.csv(matched_decision,file.path(out_dir,"08_equity_rate_cf_stable_matched_decision.csv"),row.names=FALSE)
} else {
  matched <- data.frame(); matched_decision <- data.frame()
}

# Focus tables.
diagnostic_date <- if ("2022Q1" %in% selected_dates) "2022Q1" else tail(selected_dates,1)
h_focus <- if (12L %in% focus_h) 12L else max(focus_h)
focus_equity <- comp[comp$date==diagnostic_date & comp$horizon==h_focus,,drop=FALSE]
focus_rate <- rate_summary[rate_summary$date==diagnostic_date,,drop=FALSE]
write.csv(focus_equity,file.path(out_dir,paste0("FOCUS_",diagnostic_date,"_h",h_focus,"_equity_interest_rate_channel.csv")),row.names=FALSE)
write.csv(focus_rate,file.path(out_dir,paste0("FOCUS_",diagnostic_date,"_baseline_rate_IRF.csv")),row.names=FALSE)
if (nrow(matched)) {
  focus_matched <- matched[matched$date==diagnostic_date & matched$horizon==h_focus,,drop=FALSE]
  write.csv(focus_matched,file.path(out_dir,paste0("FOCUS_",diagnostic_date,"_h",h_focus,"_rate_cf_stable_matched.csv")),row.names=FALSE)
}

save(eq_direct,eq_cumulative,rate_direct,rho_arr,solve_ok,used_draw,selected_dates,focus_h,scenarios,
     file=file.path(out_dir,"interest_rate_channel_draw_arrays.rda"))

# -----------------------------------------------------------------------------
# Human-readable diagnosis
# -----------------------------------------------------------------------------
fmt <- function(x,digits=4) {
  if (!length(x)||!is.finite(x)) return("NA")
  format(round(x,digits),nsmall=digits,trim=TRUE)
}

cf3 <- decision[decision$date==diagnostic_date & decision$horizon==h_focus & decision$scenario=="RATE_CF3_freeze_all_country_rate_path",,drop=FALSE]
full_d <- decision[decision$date==diagnostic_date & decision$horizon==h_focus & decision$scenario=="FULL",,drop=FALSE]
rate_focus_counts <- rate_sign_counts[rate_sign_counts$date==diagnostic_date,,drop=FALSE]

report <- c(
  "TVP-GVAR INTEREST-RATE CHANNEL DIAGNOSTIC — NO MCMC",
  "===================================================",
  paste0("Posterior: ",posterior_file),
  paste0("IRF: ",irf_file),
  paste0("Dates: ",paste(selected_dates,collapse=", ")),
  paste0("Shock: +",shock_pct,"% GL_gpr"),
  paste0("Maximum FULL-vs-saved IRF reconstruction error: ",format(max_baseline_reproduction_error,scientific=TRUE,digits=6)),
  "Original stable draws held fixed across scenarios: YES",
  paste0("Counterfactual stability recomputed: ",check_cf_stability),
  "",
  paste0("BASELINE RATE RESPONSES: ",diagnostic_date),
  "Negative rate median means the GPR shock lowers the country rate at that horizon."
)
if (nrow(rate_focus_counts)) {
  for (ii in seq_len(nrow(rate_focus_counts))) {
    d <- rate_focus_counts[ii,]
    report <- c(report,paste0(
      "h=",d$horizon," | negative rate medians=",d$negative_rate_median_countries,"/",d$countries,
      " | significantly negative at 68%=",d$significantly_negative_68,
      " | cross-country median rate IRF=",fmt(d$median_cross_country_rate_response)
    ))
  }
}

report <- c(report,"",paste0("EQUITY FOCUS: ",diagnostic_date,", cumulative h=",h_focus))
if (nrow(full_d)) {
  report <- c(report,paste0("FULL | positive medians=",full_d$counterfactual_positive_countries,"/",full_d$countries," | median |response|=",fmt(full_d$median_abs_counterfactual)))
}
if (nrow(cf3)) {
  report <- c(report,paste0(
    "RATE PATH FROZEN | positive medians=",cf3$counterfactual_positive_countries,"/",cf3$countries,
    " | positive->nonpositive flips=",cf3$positive_to_nonpositive_flips,
    " | median |response| ratio vs FULL=",fmt(cf3$median_ratio_to_full),
    " | countries where endogenous rates SUPPORT equity=",cf3$countries_with_positive_monetary_support,"/",cf3$countries,
    " | median support=",fmt(cf3$median_monetary_support)
  ))
}

report <- c(
  report,
  "",
  "INTERPRETATION",
  "1) First confirm whether rates actually fall. If most country rate medians are not negative, a 'rate-cut supports equity' story is not supported.",
  "2) RATE_CF1/CF2 isolate direct foreign-rate loadings into each equity equation; they do NOT remove all indirect monetary transmission.",
  "3) RATE_CF3 is the main mechanism test. It forces every country rate IRF to zero at every horizon while solving the remaining system.",
  "4) If RATE_CF3 makes equity materially LOWER / more negative than FULL, endogenous rate declines are supporting the equity response.",
  "5) If RATE_CF3 changes little, rate cuts are not the main explanation; GPR/equity-network channels remain the leading mechanism.",
  "6) If RATE_CF3 makes equity MORE positive, the endogenous rate response is a negative rather than positive equity channel.",
  "7) This is a post-estimation mechanism diagnostic, not a causal monetary-policy identification exercise.",
  "",
  "PRIMARY FILES",
  "03_baseline_rate_response_sign_counts.csv",
  "05_equity_rate_channel_decision_table.csv",
  "08_equity_rate_cf_stable_matched_decision.csv",
  paste0("FOCUS_",diagnostic_date,"_h",h_focus,"_equity_interest_rate_channel.csv"),
  paste0("FOCUS_",diagnostic_date,"_baseline_rate_IRF.csv")
)
writeLines(report,file.path(out_dir,"README_interest_rate_channel.txt"))
cat(paste(report,collapse="\n"),"\n")
cat("\nOutput directory: ",out_dir,"\n",sep="")
