# Structural GPR IRF for the TVP-GVAR.
# Required ordering in the US endogenous block:
#   US_gpr, US_y, US_dp, US_r, US_de, US_deq
# The baseline normalization fixes the impact response of log(GPR) at ln(1.10),
# i.e. an exactly +10 percent global GPR shock at every historical date.

split_tvp_alpha <- function(ALPHA.draw) {
  dims <- dimnames(ALPHA.draw)[[2]]
  if (is.null(dims)) stop("ALPHA draw has no regressor dimnames.")

  get3 <- function(tag) {
    ii <- which(dims == tag)
    if (!length(ii)) stop("Missing coefficient block: ", tag)
    ALPHA.draw[, ii, , drop = FALSE]
  }

  list(
    Lambda0post = get3("Wex"),
    Lambdapost = list(get3("Wexlag1")),
    Thetapost = list(get3("Ylag1"))
  )
}

stabilize_cov <- function(S, eps = 1e-10) {
  S <- as.matrix(S)
  S <- (S + t(S)) / 2
  ev <- eigen(S, symmetric = TRUE, only.values = TRUE)$values
  mn <- min(ev)
  if (!is.finite(mn)) stop("Non-finite covariance eigenvalue.")
  if (mn <= eps) S <- S + diag(abs(mn) + eps, nrow(S))
  S
}

gpr_struct_irf <- function(maxlag, G, F, sig, x, countries,
                           horizon = 12,
                           shock_var = "US_gpr",
                           normalization = c("pct", "sd"),
                           shock_pct = 10) {
  normalization <- match.arg(normalization)
  K <- nrow(x)
  if (nrow(G) != K || ncol(G) != K) stop("Global contemporaneous G matrix is not square.")

  us_idx <- match("US", countries)
  if (is.na(us_idx)) stop("US block not found.")
  if (length(sig) != length(countries)) stop("Country covariance list and country list have different lengths.")

  S_us <- stabilize_cov(sig[[us_idx]])
  if (nrow(S_us) != 6L) stop("US covariance block must be 6x6 under GPR-first ordering.")

  # Sigma_US = L L'. With GPR first, the first column of L is the reduced-form
  # US innovation generated by one orthogonal structural GPR innovation.
  L_us <- t(chol(S_us))
  shock_us <- L_us[, 1]

  # Stack country-specific reduced-form innovations in the same block order used
  # to construct G. Only the US structural GPR shock is switched on.
  blocks <- lapply(seq_along(sig), function(i) {
    if (i == us_idx) shock_us else rep(0, nrow(sig[[i]]))
  })
  u_stack <- unlist(blocks, use.names = FALSE)
  if (length(u_stack) != K) stop("Stacked innovation dimension does not match global system.")

  impact_raw <- as.numeric(solve(G, u_stack))
  j <- match(shock_var, rownames(x))
  if (is.na(j)) stop("Shock variable not found in global vector: ", shock_var)
  if (!is.finite(impact_raw[j]) || abs(impact_raw[j]) < 1e-12) stop("Near-zero GPR impact; cannot normalize.")

  if (normalization == "pct") {
    target <- log1p(shock_pct / 100)
    impact <- impact_raw * (target / impact_raw[j])
  } else {
    impact <- if (impact_raw[j] < 0) -impact_raw else impact_raw
  }

  phi <- array(0, c(K, K, horizon + 1L))
  phi[, , 1] <- diag(K)
  if (horizon >= 1L) {
    for (h in seq_len(horizon)) {
      acc <- matrix(0, K, K)
      for (lag in seq_len(min(maxlag, h))) {
        acc <- acc + F[[lag]] %*% phi[, , h - lag + 1L]
      }
      phi[, , h + 1L] <- acc
    }
  }

  out <- sapply(seq_len(horizon + 1L), function(h) phi[, , h] %*% impact)
  rownames(out) <- rownames(x)
  colnames(out) <- 0:horizon
  out
}

get_gpr_struct_irfa_t <- function(tt, draw_i, Sig_draw_i, x, globalG, countries,
                                  horz = 12, normalization = "pct", shock_pct = 10) {
  t <- tt
  S_post <- list()

  VAR0 <- split_tvp_alpha(draw_i[[1]])
  k_i <- dim(VAR0$Lambda0post)[[3]]
  A0 <- cbind(diag(k_i), -t(VAR0$Lambda0post[t, , ]))
  W0 <- globalG[[1]]

  H <- list()
  for (kk in seq_along(VAR0$Thetapost)) {
    B0 <- cbind(t(VAR0$Thetapost[[kk]][t, , ]), t(VAR0$Lambdapost[[kk]][t, , ]))
    H[[kk]] <- B0 %*% W0
  }
  G <- A0 %*% W0
  S_post[[1]] <- Sig_draw_i[[1]][t, , ]

  if (length(Sig_draw_i) >= 2L) {
    for (i in 2:length(Sig_draw_i)) {
      VAR1 <- split_tvp_alpha(draw_i[[i]])
      k_i <- dim(VAR1$Lambda0post)[[3]]
      A1 <- cbind(diag(k_i), -t(VAR1$Lambda0post[t, , ]))
      W1 <- globalG[[i]]

      for (kk in seq_along(VAR1$Thetapost)) {
        B1 <- cbind(t(VAR1$Thetapost[[kk]][t, , ]), t(VAR1$Lambdapost[[kk]][t, , ]))
        H[[kk]] <- rbind(H[[kk]], B1 %*% W1)
      }
      G <- rbind(G, A1 %*% W1)
      S_post[[i]] <- Sig_draw_i[[i]][t, , ]
    }
  }

  F <- lapply(H, function(h) solve(G, h))
  list(IRF_post = gpr_struct_irf(
    maxlag = length(F), G = G, F = F, sig = S_post, x = x,
    countries = countries, horizon = horz,
    shock_var = "US_gpr", normalization = normalization, shock_pct = shock_pct
  ))
}
