#!/usr/bin/env Rscript

# Add an equation-specific GPR timing restriction to the estimator generated by
# 8.12/patch_BVAR_gpr_lag.R.
#
# New mode: gdp_lagged_only
#   * Non-US GDP equation: remove current global GPR_t; retain direct GPR_{t-1}.
#   * Non-US dp/r/de/deq equations: retain current global GPR_t; remove the
#     separate direct GPR_{t-1} regressor.
#   * US GDP equation: remove contemporaneous recursive US_gpr_t; retain the
#     domestic GPR lags already present in GVAR(2,1).
#   * Other US equations keep the original recursive contemporaneous ordering.
#
# This is a timing restriction, not a sign restriction. No coefficient is
# forced negative. The omitted timing coefficient is represented as an exact
# zero when the reduced equation posterior is padded back to the common system
# coefficient layout, so the existing structural IRF/stability code continues
# to work without changing its matrix dimensions.

src <- "R/BVAR_ttvp_gprlag.r"
if (!file.exists(src)) {
  stop("Missing generated estimator: ", src,
       ". Run 8.12/patch_BVAR_gpr_lag.R first.")
}

text <- paste(readLines(src, warn = FALSE), collapse = "\n")

replace_once <- function(text, pattern, replacement, label, fixed = TRUE) {
  if (fixed) {
    loc <- gregexpr(pattern, text, fixed = TRUE)[[1]]
  } else {
    loc <- gregexpr(pattern, text, perl = TRUE)[[1]]
  }
  n <- if (identical(loc[1], -1L)) 0L else length(loc)
  if (n != 1L) {
    stop("Expected exactly one ", label, ", found ", n,
         ". The generated estimator may have changed; no timing patch was written.")
  }
  if (fixed) sub(pattern, replacement, text, fixed = TRUE) else sub(pattern, replacement, text, perl = TRUE)
}

# -----------------------------------------------------------------------------
# 1) Extend the helper mode list. In gdp_lagged_only mode the existing helper
#    must KEEP the sixth lagged non-US Wex column (global GPR_{t-1}). The helper
#    already trims that column only when mode == "current_only", so extending
#    match.arg() is sufficient.
# -----------------------------------------------------------------------------
text <- replace_once(
  text,
  'mode = c("current_only", "current_and_lag")) {',
  'mode = c("current_only", "current_and_lag", "gdp_lagged_only")) {',
  "tvpgvar_wex_lag mode declaration"
)

# -----------------------------------------------------------------------------
# 2) Build an equation-specific regression design only for the new timing mode.
#    All legacy modes retain the exact original X__ = cbind(Y[,slct], X) design.
# -----------------------------------------------------------------------------
old_x_line <- '    X__ <- cbind(Y[,slct],X)'
new_x_block <- paste0(
'    Y_current <- if (length(slct)) {\n',
'      Y[, slct, drop = FALSE]\n',
'    } else {\n',
'      matrix(numeric(0), nrow = nrow(Y), ncol = 0L)\n',
'    }\n',
'    X__full <- cbind(Y_current, X)\n',
'    X__ <- X__full\n',
'    timing_drop_index <- NA_integer_\n',
'    timing_drop_label <- NA_character_\n',
'\n',
'    if (identical(gpr_lag_mode, "gdp_lagged_only")) {\n',
'      cc_timing <- Names[[nr]]\n',
'      own_names_timing <- colnames(Y)\n',
'\n',
'      if (identical(cc_timing, "US")) {\n',
'        if (length(own_names_timing) < 2L ||\n',
'            !identical(own_names_timing[1:2], c("US_gpr", "US_y"))) {\n',
'          stop("US timing restriction requires recursive order US_gpr -> US_y -> ... . Found: ",\n',
'               paste(own_names_timing, collapse = ", "))\n',
'        }\n',
'        # US GDP is equation 2. Its first contemporaneous recursive regressor\n',
'        # is US_gpr_t. Drop only that regressor; Ylag1/Ylag2 still contain GPR lags.\n',
'        if (ii == 2L) {\n',
'          timing_drop_index <- 1L\n',
'          timing_drop_label <- "US_y:drop_current_US_gpr"\n',
'        }\n',
'      } else {\n',
'        expected_y_timing <- paste0(cc_timing, "_y")\n',
'        if (!length(own_names_timing) || !identical(own_names_timing[[1]], expected_y_timing)) {\n',
'          stop("Non-US timing restriction requires GDP as the first equation for ",\n',
'               cc_timing, ". Found: ", paste(own_names_timing, collapse = ", "))\n',
'        }\n',
'\n',
'        wex_now_idx <- which(colnames(X) == "Wex")\n',
'        wex_lag1_idx <- which(colnames(X) == "Wexlag1")\n',
'        if (length(wex_now_idx) != 6L || length(wex_lag1_idx) != 6L) {\n',
'          stop("gdp_lagged_only expects six non-US current Wex columns and six Wexlag1 columns ",\n',
'               "(5 foreign macro + global GPR) for ", cc_timing,\n',
'               ". Found current=", length(wex_now_idx), ", lag1=", length(wex_lag1_idx), ".")\n',
'        }\n',
'\n',
'        if (ii == 1L) {\n',
'          # GDP: remove current GPR_t, keep GPR_{t-1}.\n',
'          x_drop <- tail(wex_now_idx, 1L)\n',
'          timing_drop_label <- paste0(cc_timing, "_y:drop_current_global_gpr")\n',
'        } else {\n',
'          # Fast-moving/non-GDP equations: keep current GPR_t, remove the\n',
'          # separate direct GPR_{t-1} regressor (same direct timing as current_only).\n',
'          x_drop <- tail(wex_lag1_idx, 1L)\n',
'          timing_drop_label <- paste0(cc_timing, "_eq", ii, ":drop_lag1_global_gpr")\n',
'        }\n',
'        timing_drop_index <- length(slct) + x_drop\n',
'      }\n',
'\n',
'      if (!is.na(timing_drop_index)) {\n',
'        if (timing_drop_index < 1L || timing_drop_index > ncol(X__full)) {\n',
'          stop("Invalid timing_drop_index=", timing_drop_index, " for ", timing_drop_label,\n',
'               "; full equation design has ", ncol(X__full), " columns.")\n',
'        }\n',
'        X__ <- X__full[, -timing_drop_index, drop = FALSE]\n',
'      }\n',
'    }'
)
text <- replace_once(text, old_x_line, new_x_block, "equation design line")

# -----------------------------------------------------------------------------
# 3) After estimating the reduced equation, pad the omitted timing coefficient
#    back as an exact zero. This restores the original common coefficient layout
#    expected by A0 reconstruction, residuals, stability diagnostics and IRFs.
# -----------------------------------------------------------------------------
old_post_block <- paste0(
'    post.ii$posterior$slct <- slct\n',
'    post.ii$posterior$A <- aperm(post.ii$posterior$A,c(2,3,1))'
)
new_post_block <- paste0(
'    post.ii$posterior$slct <- slct\n',
'    post.ii$posterior$timing_drop_index <- timing_drop_index\n',
'    post.ii$posterior$timing_drop_label <- timing_drop_label\n',
'\n',
'    A_timing <- aperm(post.ii$posterior$A, c(2, 3, 1))\n',
'    if (!is.na(timing_drop_index)) {\n',
'      full_q <- ncol(X__full)\n',
'      keep_q <- setdiff(seq_len(full_q), timing_drop_index)\n',
'      if (length(dim(A_timing)) != 3L || dim(A_timing)[2] != length(keep_q)) {\n',
'        stop("Posterior A dimension mismatch while padding timing restriction for ",\n',
'             timing_drop_label, ". A dims=", paste(dim(A_timing), collapse = "x"),\n',
'             ", expected coefficient count=", length(keep_q), ".")\n',
'      }\n',
'      A_pad <- array(0, dim = c(dim(A_timing)[1], full_q, dim(A_timing)[3]))\n',
'      A_pad[, keep_q, ] <- A_timing\n',
'      A_timing <- A_pad\n',
'\n',
'      Omega_timing <- post.ii$posterior$Omega\n',
'      if (length(dim(Omega_timing)) != 3L || dim(Omega_timing)[2] != length(keep_q)) {\n',
'        stop("Posterior Omega dimension mismatch while padding timing restriction for ",\n',
'             timing_drop_label, ". Omega dims=", paste(dim(Omega_timing), collapse = "x"),\n',
'             ", expected coefficient count=", length(keep_q), ".")\n',
'      }\n',
'      Omega_pad <- array(0, dim = c(dim(Omega_timing)[1], full_q, dim(Omega_timing)[3]))\n',
'      Omega_pad[, keep_q, ] <- Omega_timing\n',
'      post.ii$posterior$Omega <- Omega_pad\n',
'    }\n',
'    post.ii$posterior$A <- A_timing'
)
text <- replace_once(text, old_post_block, new_post_block, "posterior A storage block")

# -----------------------------------------------------------------------------
# Static validation before overwriting the generated estimator.
# -----------------------------------------------------------------------------
required_markers <- c(
  'gdp_lagged_only',
  'X__full <- cbind(Y_current, X)',
  'US_y:drop_current_US_gpr',
  'drop_current_global_gpr',
  'drop_lag1_global_gpr',
  'A_pad <- array(0',
  'Omega_pad <- array(0'
)
for (mk in required_markers) {
  if (!grepl(mk, text, fixed = TRUE)) stop("Internal timing-patch validation failed: missing marker ", mk)
}

writeLines(strsplit(text, "\n", fixed = TRUE)[[1]], src)

# Definitive syntax parse happens here, before expensive estimation.
tryCatch(
  parse(file = src),
  error = function(e) stop("Patched estimator does not parse: ", conditionMessage(e))
)

cat("GDP/GPR timing patch applied successfully to:", src, "\n")
cat("New mode: gdp_lagged_only\n")
cat("Non-US GDP: current GPR removed; direct lag-1 GPR retained.\n")
cat("Non-US non-GDP equations: current GPR retained; direct lag-1 GPR removed.\n")
cat("US GDP: contemporaneous recursive GPR removed; endogenous GPR lags retained.\n")
